# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0789d09cef73855091e3d3d754165906"
name = "Easy Bundles & Personalizer"
handle = "easy-bundles-personalizer"
application_url = "https://influenced-mapping-residential-mainstream.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://influenced-mapping-residential-mainstream.trycloudflare.com/auth/callback",
  "https://influenced-mapping-residential-mainstream.trycloudflare.com/auth/shopify/callback",
  "https://influenced-mapping-residential-mainstream.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
